In [1]:
# Numpy - Num Python

In [2]:
list1 = [1,2,3] 
type(list1)

list

In [3]:
import numpy as np

In [8]:
arr = np.array([1,2,3])
print(arr)
print(list1)

[1 2 3]
[1, 2, 3]


In [5]:
type(arr)

numpy.ndarray

In [9]:
# Finding dimensions

arr.ndim

1

In [10]:
# Arange - Printing a range of values

np.arange(13,19)

array([13, 14, 15, 16, 17, 18])

In [19]:
np.arange(13,19,2)

array([13, 15, 17])

In [11]:
range(13,19)

range(13, 19)

In [12]:
for i in range(13,19):
  print(i)

13
14
15
16
17
18


In [20]:
# linespace

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.arange(13,40,4),np.arange(13,40,4,dtype=float)

(array([13, 17, 21, 25, 29, 33, 37]),
 array([13., 17., 21., 25., 29., 33., 37.]))

In [17]:
np.zeros(10), np.ones(10,dtype=int)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [24]:
a = np.zeros(2)
a

array([0., 0.])

In [23]:
arr

array([1, 2, 3])

In [25]:
arr2 = np.array([21,31,11,0,34,34])

In [27]:
max(arr2)

34

In [26]:
# Argmax - Position of the max value

arr2.argmax()

4

In [28]:
# Argmin - Position of the min value

arr2.argmin()

3

In [29]:
# Slicing & Indexing

arr2[2]

11

In [30]:
arr2[2]=100

In [31]:
arr2

array([ 21,  31, 100,   0,  34])

In [33]:
arr2[2:4], arr2[-4:]

(array([100,   0]), array([ 31, 100,   0,  34]))

In [40]:
a = np.array([[1,3,2,4],[9,8,6,7]])
a

array([[1, 3, 2, 4],
       [9, 8, 6, 7]])

In [43]:
a[0][3]

4

In [44]:
_3d = np.array([[[1,3,2,4],[9,8,6,7],[2,4,4,5]]])
_3d

array([[[1, 3, 2, 4],
        [9, 8, 6, 7],
        [2, 4, 4, 5]]])

In [48]:
_3d[0]

array([[1, 3, 2, 4],
       [9, 8, 6, 7],
       [2, 4, 4, 5]])

In [50]:
_3d[0][2][1:4]

array([4, 4, 5])

In [47]:
_3d[0][0][3]

4

In [52]:
_3d = np.array([[[1,3,2,4],[9,8,6,7]],[[2,4,4,5],[2,4,5,6]]])
_3d

array([[[1, 3, 2, 4],
        [9, 8, 6, 7]],

       [[2, 4, 4, 5],
        [2, 4, 5, 6]]])

In [54]:
_3d[1][1]

array([2, 4, 5, 6])

In [35]:
a.ndim

2

In [38]:
a = np.array([[[[[[1,3,2,4],[9,8,6,7],[23,32,56,3]]]]]])
a

array([[[[[[ 1,  3,  2,  4],
           [ 9,  8,  6,  7],
           [23, 32, 56,  3]]]]]])

In [39]:
a.ndim

6

In [ ]:
# Reshape

In [55]:
a = np.arange(12)  # Posib (6*2,4*3)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
"""
4 - M , 6 - F

Name, Age, Salary
aaa    54    ?
yyy    ?    50k
"""

In [64]:
np.random.rand(1)

array([0.61338953])

In [ ]:
np.random.randint()

In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a.sum()

66

In [67]:
# Sqrt & Log

np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [68]:
np.log(a)

<ipython-input-68-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [69]:
np.log10(a)

<ipython-input-69-c769c8e1eb64>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269])

In [71]:
# absolute

a = -32
np.abs(a)

32

In [ ]:
# Pandas -- Data Manupulation

# pandas--->1) Series & 2) DataFrame

In [72]:
import pandas as pd


In [84]:
s = pd.Series(np.random.rand(6))
s

0    0.210635
1    0.238948
2    0.436056
3    0.770767
4    0.176652
5    0.569349
dtype: float64

In [74]:
s[4]

0.742271504015138

In [75]:
s[2:4]

2    0.49715
3    0.23125
dtype: float64

In [76]:
s[0]=1234
s

0    1234.000000
1       0.133489
2       0.497150
3       0.231250
4       0.742272
5       0.167842
dtype: float64

In [85]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [86]:
s.index = ['a','b','c','d','e',4]

In [79]:
s

a    1234.000000
b       0.133489
c       0.497150
d       0.231250
e       0.742272
4       0.167842
dtype: float64

In [81]:
s['b']

0.13348917257032644

In [87]:
s['b':]

b    0.238948
c    0.436056
d    0.770767
e    0.176652
4    0.569349
dtype: float64

In [82]:
s['b':'e']

b    0.133489
c    0.497150
d    0.231250
e    0.742272
dtype: float64

In [92]:
s[2]

KeyError: ignored

In [93]:
s[2:4]

c    0.436056
d    0.770767
dtype: float64

In [89]:
s[-4:-1]

c    0.436056
d    0.770767
e    0.176652
dtype: float64

In [83]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 4], dtype='object')

In [96]:
s['a':'e':2]

a    0.210635
c    0.436056
e    0.176652
dtype: float64

In [94]:
s1 = pd.Series(np.random.rand(12))
s1

0     0.184589
1     0.308427
2     0.803336
3     0.682931
4     0.757522
5     0.599663
6     0.685694
7     0.140286
8     0.887140
9     0.903150
10    0.960772
11    0.462501
dtype: float64

In [95]:
s1[1:9:2]

1    0.308427
3    0.682931
5    0.599663
7    0.140286
dtype: float64